# Barbara (σ=20) — coarse sweep
dataset:
  images:
    - data/USC_SIPI/barbarag.bmp
  sigma: 20

defaults:
  device: cuda
  dtheta: 2.0
  dt: 0.05
  iters: 18
  mu: 5.0
  lam: 1.2        # 纹理更强时，横向尺度略放大

search:
  k:     [0.25, 0.3, 0.35, 0.4, 0.45]
  h:     [0.08, 0.10, 0.12, 0.14]
  a:     [0.18, 0.20, 0.22, 0.24]
  lam:   [1.0, 1.2]
  iters: [14, 16, 18, 20, 22, 24]
  mu:    [5.0]

ref_metric: ssim
runs_dir: runs
