# Barbara (σ=20) — refine around best region
dataset:
  images:
    - data/USC_SIPI/barbarag.bmp
  sigma: 20

defaults:
  device: cuda
  dtheta: 2.0
  dt: 0.05
  iters: 20
  mu: 5.0
  lam: 1.2

search:
  k:     [0.25, 0.30, 0.35, 0.40, 0.45]
  h:     [0.09, 0.10, 0.11, 0.12]
  a:     [0.19, 0.2, 0.21, 0.22]
  lam:   [1.1, 1.2, 1.3]
  dt:    [0.05, 0.06, 0.07]
  iters: [13, 14, 15, 16, 17, 18, 19, 20]
  mu:    [5.0]

ref_metric: ssim
runs_dir: runs
