dataset:
  images:
    - data/USC_SIPI/man.tiff
  sigma: 10
defaults:
  dtheta: 2
  dt: 0.05
  mu: 5
  lam: 1
  device: cuda
search:
  iters: [4, 6, 8, 10, 12]
  k: [0.25, 0.3, 0.35]
  h: [0.08, 0.1, 0.12]
  a: [0.1]
ref_metric: psnr
